<div class="buyer_term">
    <div class="buyers_terms" id="buyer_terms">
        <h3> Buyer Terms and Conditions </h3>
        <p>Last updated on: September 13, 2016</p>
        <p>By signing up to the Tagzie Limited (“Tagzie”) service as a buyer (“Service”) or any of the services offered by Tagzie you agree to be bound by the following terms and conditions (“Terms of Use”). The Services offered by Tagzie under these Terms of Use include facilitating the purchase of goods and services (“Products”) from our registered sellers (“Merchants”) via platforms such as social networks, the Tagzie websites or apps. Any new features or tools which are added to the current Service shall be also subject to these Terms of Use. You can review the current version of the Terms of Use at any time at https://www.tagzie.com/legal/terms. Tagzie reserves the right to update and change these Terms of Use by posting updates and changes to the Tagzie website. It is recommended that you check the Terms of Use from time to time for any updates or changes that may impact you.</p>

        <p>You must review, agree with and accept all of the terms and conditions contained in this Terms of Use agreement and Tagzie’s Privacy Policy before using the Service. All policy documents can be found online: https://www.tagzie.com/legal/terms.</p>
        <h4> 1. Account Terms </h4>
        <p>You must be 18 years or older or at least the age of majority in the jurisdiction where you reside or from which you use this Service.</p>
        <p>To access and use the Services, you must register for a Tagzie account (“Account”) by providing your full legal name, current address, phone number, a valid email address, and any other information indicated as required. Tagzie may reject your application for an Account, or cancel an existing Account, for any reason, at our sole discretion.</p>
        <p>By providing an email address (either directly, or as associated with your relevant social network profile), you acknowledge that Tagzie will use such email address as the primary method for communication, unless stated otherwise.</p>
        <p>You are responsible for keeping your password secure. Tagzie cannot and will not be liable for any loss or damage from your failure to maintain the security of your Account and password.</p>
        <p>A breach or violation of any term in the Terms of Use as determined in the sole discretion of Tagzie will result in an immediate termination of your services.</p>
        <h4>2. Account Activation</h4>
        <p>The person signing up for the Service will be the contracting party (“Account Owner”) for the purposes of these Terms of Use and will be the person who is authorised to use any corresponding account we may provide to the Account Owner in connection with the Service. If you are signing up for the Service on behalf of your employer, your employer shall be the Account Owner. If you are
            signing up for the Service on behalf of your employer, then you represent and warrant that you have the authority to bind your employer to our Terms of Use.</p>
        <h4>3. General Conditions</h4>
        <p>You must read, agree with and accept all of the terms and conditions contained in these Terms of Use and the Privacy Policy before you may become a member of Tagzie.</p>
        <p>Technical support is provided to Account holders and is only available via email. You will also be provided with the contact details of any Merchants that you purchase Products from.</p>
        <p>The Terms of Use shall be governed by and interpreted in accordance with the laws of England and Wales. The parties irrevocably and unconditionally submit to the exclusive jurisdiction of the courts of England and Wales with respect to any dispute or claim arising out of or in connection with the Terms of Use.</p>
        <p>You acknowledge and agree that Tagzie may amend these Terms of Use at any time by posting the relevant amended and restated Terms of Use on Tagzie’s website, available at https://www.tagzie.com/legal/terms and such amendments to the Terms of Use are effective as of the date of posting. Your continued use of the Services after the amended Terms of Use are posted to Tagzie’s website constitutes your agreement to, and acceptance of, the amended Terms of Use. If you do not agree to any changes to the Terms of Use, do not continue to use the Service, and contact us at <a href="mailto:support@tagzie.com">support@tagzie.com</a> to arrange the termination of your account.</p>
        <p>You may not use the Tagzie service for any illegal or unauthorised purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws) or the laws of England and Wales. You will comply with all applicable laws, rules and regulations in your use of the Service.</p>
        <p>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service without the express written permission by Tagzie.</p>
        <p>Questions about the Terms of Use should be sent to <a href="mailto:support@tagzie.com">support@tagzie.com.</a></p>
        <p>Any personal data, including Credit Card information, is provided to Tagzie as the data controller, and our payment processor, Stripe Payments UK, Limited (“Stripe”) as the data processor. As data controller, Tagzie will be registered with the Information Commissioner’s Office by October 20th 2016 and this policy will be updated with our registration information. We comply with our obligations under the Data Protection Act 1998. As data processor, Stripe transfers personal data (including cardholder data) to its affiliate, Stripe Inc, which stores and processes this personal data on servers located in the US. To ensure the adequate protection of data transferred outside of EU member states, Stripe employs appropriate mechanisms to allow for the lawful onward transfer of personal data under the EU Data Directive. By using the Service, you consent to Tagzie sharing your personal data with Stripe, including information that we may collect directly from you, or via cookies or other means.</p>
        <p>You acknowledge and agree that your use of the Service, including information transmitted to or stored by Tagzie, is governed by our privacy policy at https://www.tagzie.com/legal/privacy
            The Terms of Use may be available in languages other than English. In the case of any inconsistencies or conflicts between these English Terms of Use and Tagzie’s Terms of Use available in another language, the current English version will prevail.</p>
        <p>All activity and conduct via the Service must be in accordance with our Buying Guidelines, available online by October 20th 2016. This policy will be updated when Buying Guidelines are published.</p>
        <p>Any off-platforms purchases that you make or attempt to make is not permitted and persistent off-platform purchases may result, at Tagzie’s sole discretion, in the termination of your account.</p>
        <h4>4. Tagzie Rights </h4>
        <p>We reserve the right to modify or terminate the Service for any reason, without notice at any time.</p>
        <p>We reserve the right to refuse service to anyone for any reason at any time.</p>
        <p>Verbal or written abuse of any kind (including threats of abuse or retribution) of any Tagzie customer, Tagzie employee, member or officer will result in immediate Account termination.</p>
        <p>Tagzie does not pre-screen Posted Content and it is in our sole discretion to refuse or remove any Posted Content that is available via the Service.</p>
        <p>In the event of a dispute regarding Account ownership, we reserve the right to request documentation to determine or confirm Account ownership. Documentation may include, but is not limited to, a certified copy of your government issued photo ID, the last four digits of the credit card on file, a certified copy of a recent utility bill etc.</p>
        <p>Tagzie retains the right to determine, in our sole judgment, rightful Account ownership and transfer an Account to the rightful owner. If we are unable to reasonably determine the rightful Account owner, Tagzie reserves the right to temporarily disable an Account until resolution has been determined between the disputing parties.</p>
        <h4>5. Limitation of Liability </h4>
        <p>You expressly agree that Tagzie shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses resulting from the use of or inability to use the service.</p>
        <p>In no event shall Tagzie or our suppliers be liable for lost profits or any special, incidental or consequential damages arising out of or in connection with our site, our services or these Terms of Use (however arising including negligence). You agree to indemnify and hold us and (as applicable) our parent, subsidiaries, affiliates, Tagzie partners, officers, directors, agents, employees and suppliers harmless from any claim or demand, including reasonable legal fees, made by any third party due to or arising out of your breach of these Terms of Use or the documents it incorporates by reference, or your violation of any law or the rights of a third party.</p>
        <p>Your use of the Service is at your sole risk. The Service is provided on an “as is” and “as available” basis without any warranty or condition, express, implied or statutory.</p>
        <p>Tagzie does not warrant that the Service will be uninterrupted, timely, secure, or error-free.</p>
        <p>Tagzie does not warrant that the results that may be obtained from the use of the Service will be accurate or reliable.</p>
        <p>Tagzie does not warrant that the quality of any products, services, information, or other material purchased or obtained by you through the Service will meet your expectations, or that any errors in the Service will be corrected.</p>
        <p>Tagzie will not be liable for any issues caused by events such as fires, telecommunications or internet failures, utility failures, power failures, equipment failures, employment strife, riots, war, terrorist attack, non-performance or our payment processor, acts of God, or other causes over which Tagzie has no reasonable control.</p>
        <h4>6. Waiver and Complete Agreement</h4>
        <p>The failure of Tagzie to exercise or enforce any right or provision of the Terms of Use shall not constitute a waiver of such right or provision. The Terms of Use constitutes the entire agreement between you and Tagzie and govern your use of the Service, superseding any prior agreements between you and Tagzie (including, but not limited to, any prior versions of the Terms of Use).
        <h4>7. Intellectual Property</h4>
        <p>We will not disclose your confidential information to third parties, except as required in the course of providing our services. Confidential information includes any materials or information provided by you to us which is not publicly known. Confidential information does not include information that: (a) was in the public domain at the time we received it; (b) comes into the public domain after we received it through no fault of ours; (c) we received from someone other than you without breach of our or their confidentiality obligations; or (d) we are required to disclose by law.</p>
        <p>Under no circumstances shall Tagzie be liable for any direct, indirect, incidental, special, consequential, exemplary or other damages whatsoever, including, without limitation damages that result from any transaction via the Service or any resulting contractual relationship between yourself and a Merchant. These limitations shall apply even if Tagzie has been advised of the possibility of such damages. The foregoing limitations shall apply to the fullest extent permitted by law.</p>
        <h4>8. Cancellation and Termination</h4>
        <p>You may cancel your Account at any time by emailing support@tagzie.com and following the instructions which will be provided in Tagzie's response.</p>
        <p>Upon termination of the Services by either party for any reason, Tagzie will cease providing you with the Services and you will no longer be able to use the Service.</p>
        <p>We reserve the right to modify or terminate the Tagzie Service or your Account for any reason, without notice at any time.</p>
        <p>Without limiting any other remedies, Tagzie may suspend or terminate your Account if we suspect that you (by conviction, settlement, insurance or escrow investigation, or otherwise) have engaged in fraudulent activity in connection with the Site.</p>
        <p>If your Instagram or other relevant social media account is terminated for any reason, your Tagzie account will remain active. You may continue to access your Existing purchases, but will not be able to make any new purchases. You will need to contact Tagzie (email support@tagzie.com) so an alternative means of login can be arranged.</p>
        <h4>9. Modifications</h4>
        <p>Tagzie reserves the right at any time, and from time to time, to modify or discontinue the Service (or any part thereof) with or without notice.</p>
        <h4>10. Third Party Services</h4>
        <p>In addition to these Terms of Use, you also agree to be bound by the additional service-specific terms applicable to services you purchase from, or that are provided by, Tagzie’s partners or other third parties.</p>
        <p>Tagzie may from time to time recommend, provide you with access to, or enable third party software, applications (“Apps”), products, services or website links (collectively, “Third Party Services”) for your consideration or use. Such Third Party Services are made available only as a convenience, and your purchase, access or use of any such Third Party Services is solely between you and the applicable third party services provider (“Third Party Provider”). Any use by you of Third Party Services offered through the Services or Tagzie’s website is entirely at your own risk and discretion, and it is your responsibility to read the terms and conditions and/or privacy policies applicable to such Third Party Services before using them.</p>
        <p>We do not provide any warranties with respect to Third Party Services. You acknowledge that Tagzie has no control over Third Party Services, and shall not be responsible or liable to anyone for such Third Party Services. The availability of Third Party Services on Tagzie’s websites, including the Tagzie app, or the integration or enabling of such Third Party Services with the Services does not constitute or imply an endorsement, authorization, sponsorship, or affiliation by or with Tagzie. Tagzie strongly recommends that you seek specialist advice before using or relying on Third Party Services, to ensure they will meet your needs. In particular, tax calculators should be used for reference only and not as a substitute for independent tax advice when assessing the correct tax rates you should charge to your customers.</p>
        <p>If you install or enable a Third Party Service for use with the Services, you grant us permission to allow the applicable Third Party Provider to access your data and to take any other actions as required for the interoperation of the Third Party Service with the Services, and any exchange of data or other interaction between you and the Third Party Provider is solely between you and such Third Party Provider. Tagzie is not responsible for any disclosure, modification or deletion of your data or Posted Content, or for any corresponding losses or damages you may suffer, as a result of access by a Third Party Service or a Third Party Provider to your data or Posted Content.</p>
        <p>Under no circumstances shall Tagzie be liable for any direct, indirect, incidental, special, consequential, punitive, extraordinary, exemplary or other damages whatsoever that result from any Third Party Services or your contractual relationship with any Third Party Provider, including any Expert. These limitations shall apply even if Tagzie has been advised of the possibility of such damages. The foregoing limitations shall apply to the fullest extent permitted by applicable law.</p>
        <p>You agree to indemnify and hold us and (as applicable) our parent, subsidiaries, affiliates, Tagzie partners, officers, directors, agents, employees, and suppliers harmless from any claim or demand, including reasonable legal fees, arising out of your use of a Third Party Service or your relationship with a Third Party Provider.</p>
        <h4> 11. IP Infringement and Takedown Procedure</h4>
        <p>Tagzie supports the protection of intellectual property. It's our policy to respond to all notices of alleged copyright infringement. If you believe that one of our merchants are infringing upon your intellectual property rights, you can send an infringement notice to us by contacting <a href="mailto:copyright@tagzie.com">copyright@tagzie.com.</a> Upon receiving an infringement, we may remove or disable access to the material claimed to be a copyright infringement. Once provided with a notice of takedown, the merchant can reply with a counter notification using our form if they object to the complaint. You, as the original complainant, then have 14 business days after we receive a counter notification to seek a court order restraining the merchant from engaging in the infringing activity, otherwise we will restore the material. For more information, please contact us at <a href="mailto:copyright@tagzie.com">copyright@tagzie.com.</a></p>
    </div>
</div>